[package]
name = "Mutations"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
opt-level = "z"
lto = true

[profile.release]
strip = "symbols"
panic = "abort"
opt-level = "z"
lto = true

[lib]
crate-type = ["staticlib"]  # or "cdylib" if you prefer a DLL